import 'package:ayura/provider/models/meal.dart';

List<Meal> mealList = [
  Meal(
    mealId: '1',
    name: 'Green gram milk rice',
    image: 'assets/images/mealPlan/greengramrice.png',
    mainmass: 135.0,
    sidemass: 15.0,
    protein: 6.9,
    carbs: 32.1,
    fat: 7.2,
    calories: 213,
  ),
  Meal(
    mealId: '2',
    name: 'String Hoppers',
    image: 'assets/images/mealPlan/redstringhoppers.png',
    mainmass: 180.0,
    sidemass: 160.0,
    protein: 18.1,
    carbs: 120.5,
    fat: 49.2,
    calories: 968,
  ),
  Meal(
    mealId: '3',
    name: 'Boiled Cowpea',
    image: 'assets/images/mealPlan/cowpea.png',
    mainmass: 200.0,
    sidemass: 0.0,
    protein: 5.6,
    carbs: 75.6,
    fat: 13.2,
    calories: 425,
  ),
  Meal(
    mealId: '4',
    name: 'Itly',
    image: 'assets/images/mealPlan/pittu.png',
    mainmass: 200.0,
    sidemass: 0.0,
    protein: 5.6,
    carbs: 75.6,
    fat: 13.2,
    calories: 425,
  ),
  Meal(
    mealId: '4',
    name: 'Boiled Cowpea',
    image: 'assets/images/mealPlan/hoppers.png',
    mainmass: 200.0,
    sidemass: 0.0,
    protein: 5.6,
    carbs: 75.6,
    fat: 13.2,
    calories: 425,
  ),
  Meal(
    mealId: '3',
    name: 'Boiled Cowpea',
    image: 'assets/images/mealPlan/ricepancake.png',
    mainmass: 200.0,
    sidemass: 0.0,
    protein: 5.6,
    carbs: 75.6,
    fat: 13.2,
    calories: 425,
  ),

  // Add more meals here...
];
